name: am


services:
  mysql:
    logging:
      driver: syslog
      options:
        tag: "am-mysql"

  gearmand:
    logging:
      driver: syslog
      options:
        tag: "am-gearman"

  clamavd:
     logging:
      driver: syslog
      options:
        tag: "am-clamav"

  elasticsearch:
    logging:
      driver: syslog
      options:
        tag: "am-elasticsearch"

  nginx:
    logging:
      driver: syslog
      options:
        tag: "am-nginx"

  archivematica-storage-service:
    user: $UID:$UID
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    environment:
      SS_GUNICORN_GROUP: "$UID"
      SS_GUNICORN_USER: "$UID"
    logging:
      driver: syslog
      options:
        tag: "am-ss"

  archivematica-dashboard:
    user: $UID:$UID
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    environment:
      AM_GUNICORN_USER: "$UID"
      AM_GUNICORN_GROUP: "$UID"
    logging:
      driver: syslog
      options:
        tag: "am-dashboard"

  archivematica-mcp-server:
    user: $UID:$UID
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    logging:
      driver: syslog
      options:
        tag: "am-mcp-server"

  archivematica-mcp-client:
    user: $UID:$UID
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    logging:
      driver: syslog
      options:
        tag: "am-mcp-client"

  archivematica-storage-service-migrations:
    user: $UID:$UID
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    environment:
      SS_GUNICORN_GROUP: "$UID"
      SS_GUNICORN_USER: "$UID"
    logging:
      driver: syslog
      options:
        tag: "am-ss-migrations"

  archivematica-dashboard-migrations:
    user: $UID:$UID
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    environment:
      SS_GUNICORN_GROUP: "$UID"
      SS_GUNICORN_USER: "$UID"
    logging:
      driver: syslog
      options:
        tag: "am-dashboard-migrations"

  archivematica-storage-service-bootstrap:
    user: $UID:$UID
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    environment:
      SS_GUNICORN_GROUP: "$UID"
      SS_GUNICORN_USER: "$UID"


    logging:
      driver: syslog
      options:
        tag: "am-ss-bootstrap"


  archivematica-dashboard-bootstrap:
    user: $UID:$UID
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    environment:
      AM_GUNICORN_USER: "$UID"
      AM_GUNICORN_GROUP: "$UID"

    logging:
      driver: syslog
      options:
        tag: "am-dashboard-bootstrap"

