---

# Basic docker-compose file for running a ocal instance of Archivematica.

# This file is based on the one at
# https://github.com/artefactual/archivematica/blob/stable/1.18.x/hack/docker-compose.yml


# The name of the project, used to prefix container names and network names.
name: am


volumes:

  # Internal named volumes.
  # These are not accessible outside of the docker host and are maintained by
  # Docker.

  archivematica_storage_service_staging_data:
    driver: local
    driver_opts:
      type: none
      device: ${ARCHIVEMATICA_SS_STAGING:-.storage_service}
      o: bind

  archivematica_pipeline_data:
    driver: local
    driver_opts:
      type: none
      device: ${ARCHIVEMATICA_SHAREDDIRECTORY:-.sharedDirectory}
      o: bind
  
services:


  gearmand:
    image: "artefactual/gearmand:1.1.22-alpine"
    command: "--queue-type=builtin"
    user: "gearman"
    ports:
      - "127.0.0.1:62004:4730"
  
  archivematica-storage-service:
    image: "artefactual/archivematica-storage-service:v0.24.0"
    platform: "linux/amd64"
    env_file: ss-env
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      archivematica-storage-service-bootstrap:
         condition: service_completed_successfully
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - "archivematica_storage_service_staging_data:/var/archivematica/storage_service:rw"
      - "${ARCHIVEMATICA_SS_TRANSFER_SOURCE:-./}:/home:rw"
      - "./AIPsStore:/var/archivematica/sharedDirectory/www/AIPsStore"
      - "./DIPsStore:/var/archivematica/sharedDirectory/www/DIPsStore"
      - /var/lib/mysql/:/var/run/mysqld/
      # Other folders can be mounted to be available in the tranfer source:
      # - "~/Downloads:/home/Downloads"

  archivematica-dashboard:
    image: "artefactual/archivematica-dashboard:v1.18.0"
    platform: "linux/amd64"
    env_file: dashboard-env
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/8000; exit $?;'"
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      archivematica-dashboard-bootstrap:
         condition: service_completed_successfully
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - /var/lib/mysql/:/var/run/mysqld/
    links:
      - "gearmand"
      - "archivematica-storage-service"

  archivematica-mcp-server:
    image: "artefactual/archivematica-mcp-server:v1.18.0"
    platform: "linux/amd64"
    env_file: mcp-server-env
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/7999; exit $?;'"
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      archivematica-dashboard:
        condition: service_healthy
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - "./AIPsStore:/var/archivematica/sharedDirectory/www/AIPsStore"
      - "./DIPsStore:/var/archivematica/sharedDirectory/www/DIPsStore"
      - /var/lib/mysql/:/var/run/mysqld/
    links:
      - "gearmand"

  archivematica-mcp-client:
    image: "artefactual/archivematica-mcp-client:v1.18.0"
    platform: "linux/amd64"
    env_file: mcp-client-env
    depends_on:
      archivematica-mcp-server:
        condition: service_healthy
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - /var/lib/mysql/:/var/run/mysqld/
    links:
      - "gearmand"
      - "archivematica-storage-service"


  # Migrations containers
  # We run them always to ensure migrations in new versions take effect

  archivematica-storage-service-migrations:
    image: "artefactual/archivematica-storage-service:v0.24.0"
    platform: "linux/amd64"
    env_file: ss-env
    entrypoint:
       - python3
       - -m
       - archivematica.storage_service.manage
       - migrate
       - --noinput
    volumes:
      - /var/lib/mysql/:/var/run/mysqld/


  archivematica-dashboard-migrations:
    image: "artefactual/archivematica-dashboard:v1.18.0"
    platform: "linux/amd64"
    env_file: dashboard-env
    entrypoint:
       - python3
       - -m
       - archivematica.dashboard.manage
       - migrate
       - --noinput
    volumes:
      - /var/lib/mysql/:/var/run/mysqld/


  # Bootstrap commands
  # Those are only needed the first time the system is registered

  archivematica-storage-service-bootstrap:
    image: "artefactual/archivematica-storage-service:v0.24.0"
    platform: "linux/amd64"
    env_file: ss-env
    entrypoint:
       - python3
       - -m
       - archivematica.storage_service.manage
       - create_user
       - --username=${ARCHIVEMATICA_SS_USER:-test}
       - --password=${ARCHIVEMATICA_SS_PASSWORD:-test}
       - --email=${ARCHIVEMATICA_SS_EMAIL:-test}
       - --api-key=${ARCHIVEMATICA_SS_APIKEY:-test}
       - --superuser
    depends_on:
      archivematica-storage-service-migrations:
         condition: service_completed_successfully
    volumes:
      - /var/lib/mysql/:/var/run/mysqld/

  archivematica-dashboard-bootstrap:
    image: "artefactual/archivematica-dashboard:v1.18.0"
    platform: "linux/amd64"
    env_file: dashboard-env
    entrypoint:
       - python3
       - -m
       - archivematica.dashboard.manage
       - install
       - --username=${ARCHIVEMATICA_DASHBOARD_USER:-test}
       - --password=${ARCHIVEMATICA_DASHBOARD_PASSWORD:-test}
       - --email=${ARCHIVEMATICA_DASHBOARD_EMAIL:-test}
       - --org-name=${ARCHIVEMATICA_DASHBOARD_ORG_NAME:-test}
       - --org-id=${ARCHIVEMATICA_DASHBOARD_ORG_ID:-test}
       - --api-key=${ARCHIVEMATICA_DASHBOARD_API_KEY:-test}
       - --ss-url=http://archivematica-storage-service:8000
       - --ss-user=${ARCHIVEMATICA_SS_USER:-test}
       - --ss-api-key=${ARCHIVEMATICA_SS_APIKEY:-test}
       - --site-url=http://archivematica-dashboard:8000
    depends_on:
      archivematica-dashboard-migrations:
         condition: service_completed_successfully
      archivematica-storage-service:
         condition: service_healthy
    links:
      - "archivematica-storage-service"
    volumes:
      - /var/lib/mysql/:/var/run/mysqld/
