---

# Basic docker-compose file for running a local instance of Archivematica.

# This file is based on the one at
# https://github.com/artefactual/archivematica/blob/stable/1.18.x/hack/docker-compose.yml


# The name of the project, used to prefix container names and network names.
name: am


volumes:

  # Internal named volumes.
  # These are not accessible outside of the docker host and are maintained by
  # Docker.
  clamavd_data:
  mysql_data:

  archivematica_storage_service_staging_data:
    driver: local
    driver_opts:
      type: none
      device: ${ARCHIVEMATICA_SS_STAGING:-.storage_service}
      o: bind

  archivematica_pipeline_data:
    driver: local
    driver_opts:
      type: none
      device: ${ARCHIVEMATICA_SHAREDDIRECTORY:-.sharedDirectory}
      o: bind
  


include:
  - archivematica/bootstrap.yml 

services:

  mysql:
    image: "percona/percona-server:8.4.10-10"
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_USER: "archivematica"
      MYSQL_PASSWORD: "demo"
    volumes:
      - "./.etc/mysql/tuning.cnf:/etc/my.cnf.d/tuning.cnf:ro"
      - "mysql_data:/var/lib/mysql"
    ports:
      - "127.0.0.1:62001:3306"
    cap_add:
      - "SYS_NICE"
    healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
       timeout: 10s
       retries: 10

  archivematica-storage-service:
    image: "${STORAGE_SERVICE_IMAGE:-artefactual/archivematica-storage-service:v0.24.0}"
    platform: "linux/amd64"
    env_file: "archivematica/ss-env"
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      archivematica-storage-service-bootstrap:
         condition: service_completed_successfully
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - "archivematica_storage_service_staging_data:/var/archivematica/storage_service:rw"
      - "${ARCHIVEMATICA_SS_TRANSFER_SOURCE:-./}:/home:rw"
      - "./AIPsStore:/var/archivematica/sharedDirectory/www/AIPsStore"
      - "./DIPsStore:/var/archivematica/sharedDirectory/www/DIPsStore"
      # Other folders can be mounted to be available in the tranfer source:
      # - "~/Downloads:/home/Downloads"
    links:
      - "mysql"

  archivematica-dashboard:
    image: "${DASHBOARD_IMAGE:-artefactual/archivematica-dashboard:v1.18.0}"
    platform: "linux/amd64"
    env_file: "archivematica/dashboard-env"
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/8000; exit $?;'"
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      archivematica-dashboard-bootstrap:
         condition: service_completed_successfully
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"

    links:
      - "mysql"
      - "gearmand"
      - "archivematica-storage-service"

  archivematica-mcp-server:
    image: "${MCP_SERVER_IMAGE:-artefactual/archivematica-mcp-server:v1.18.0}"
    platform: "linux/amd64"
    env_file: "archivematica/mcp-server-env"
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/7999; exit $?;'"
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      archivematica-dashboard:
        condition: service_healthy
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - "./AIPsStore:/var/archivematica/sharedDirectory/www/AIPsStore"
      - "./DIPsStore:/var/archivematica/sharedDirectory/www/DIPsStore"
    links:
      - "mysql"
      - "gearmand"

  archivematica-mcp-client:
    image: "${MCP_CLIENT_IMAGE:-artefactual/archivematica-mcp-client:v1.18.0}"
    platform: "linux/amd64"
    env_file: "archivematica/mcp-client-env"
    depends_on:
      archivematica-mcp-server:
        condition: service_healthy
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"
      - "archivematica-storage-service"

  gearmand:
    image: "artefactual/gearmand:1.1.22-alpine"
    command: "--queue-type=builtin"
    user: "gearman"
    ports:
      - "127.0.0.1:62004:4730"

  clamavd:
    image: "clamav/clamav-debian:1.5.3"
    user: "clamav"
    entrypoint: "/init-unprivileged"
    environment:
      CLAMD_CONF_MaxFileSize: "42M"
      CLAMD_CONF_MaxScanSize: "42M"
      CLAMD_CONF_StreamMaxLength: "100M"
    deploy:
      resources:
        limits:
          memory: 4096M
    ports:
      - "127.0.0.1:62006:3310"
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:ro"
      - "clamavd_data:/var/lib/clamav/:rw"

  nginx:
    image: "nginx:1.29.1"
    volumes:
      - "./.etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./.etc/nginx/conf.d/archivematica.conf:/etc/nginx/conf.d/archivematica.conf:ro"
      - "./.etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "62080:80"
      - "62081:8000"



