---

# Basic docker-compose file for running a local instance of Archivematica.

# This file is based on the one at
# https://github.com/artefactual/archivematica/blob/stable/1.18.x/hack/docker-compose.yml


# The name of the project, used to prefix container names and network names.
name: am


volumes:

  # Internal named volumes.
  # These are not accessible outside of the docker host and are maintained by
  # Docker.
  clamavd_data:
  mysql_data:

  archivematica_storage_service_staging_data:
    driver: local
    driver_opts:
      type: none
      device: ${ARCHIVEMATICA_SS_STAGING:-.storage_service}
      o: bind

  archivematica_pipeline_data:
    driver: local
    driver_opts:
      type: none
      device: ${ARCHIVEMATICA_SHAREDDIRECTORY:-.sharedDirectory}
      o: bind
  


services:

  mysql:
    image: "percona/percona-server:8.4.10-10"
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_USER: "archivematica"
      MYSQL_PASSWORD: "demo"
    volumes:
      - "./.etc/mysql/tuning.cnf:/etc/my.cnf.d/tuning.cnf:ro"
      - "mysql_data:/var/lib/mysql"
    ports:
      - "127.0.0.1:62001:3306"
    cap_add:
      - "SYS_NICE"
    healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
       timeout: 10s
       retries: 10
  mysql-archivematica-db:
    image: "percona/percona-server:8.4.10-10"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_USER: "archivematica"
      MYSQL_PASSWORD: "demo"
    volumes:
      - "./.etc/mysql/tuning.cnf:/etc/my.cnf.d/tuning.cnf:ro"
      - "mysql_data:/var/lib/mysql"
    entrypoint:
      - /bin/sh
      - -c
      - |
        mysql -uroot -p$${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS MCP CHARACTER SET utf8 COLLATE utf8_unicode_ci;
                     CREATE DATABASE IF NOT EXISTS SS CHARACTER SET utf8 COLLATE utf8_unicode_ci;
                     GRANT ALL ON MCP.* TO 'archivematica'@'%';
                     GRANT ALL ON SS.* TO 'archivematica'@'%';"
    depends_on:
      mysql:
        condition: service_healthy

  gearmand:
    image: "artefactual/gearmand:1.1.22-alpine"
    command: "--queue-type=builtin"
    user: "gearman"
    ports:
      - "127.0.0.1:62004:4730"
  
  clamavd:
    image: "clamav/clamav-debian:1.5.3"
    user: "clamav"
    entrypoint: "/init-unprivileged"
    environment:
      CLAMD_CONF_MaxFileSize: "42M"
      CLAMD_CONF_MaxScanSize: "42M"
      CLAMD_CONF_StreamMaxLength: "100M"
    deploy:
      resources:
        limits:
          memory: 4096M
    ports:
      - "127.0.0.1:62006:3310"
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:ro"
      - "clamavd_data:/var/lib/clamav/:rw"

  
  nginx:
    image: "nginx:1.29.1"
    volumes:
      - "./.etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./.etc/nginx/conf.d/archivematica.conf:/etc/nginx/conf.d/archivematica.conf:ro"
      - "./.etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "62080:80"
      - "62081:8000"

  archivematica-storage-service:
    image: "artefactual/archivematica-storage-service:v0.24.0"
    platform: "linux/amd64"
    environment: &ss-env
    # Full list at https://github.com/artefactual/archivematica-storage-service/tree/stable/0.24.x/install#environment-variables
      FORWARDED_ALLOW_IPS: "*"
      SS_GUNICORN_ACCESSLOG: "/dev/null"
      DJANGO_SETTINGS_MODULE: "archivematica.storage_service.storage_service.settings.local"
      SS_DB_URL: "mysql://archivematica:demo@mysql/SS"
      SS_GNUPG_HOME_PATH: "/var/archivematica/storage_service/.gnupg"
      SS_PROMETHEUS_ENABLED: "true"
      SS_AUDIT_LOG_MIDDLEWARE: "true"
      SESSION_COOKIE_SECURE: "false"
      CSRF_COOKIE_SECURE: "false"

    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      archivematica-storage-service-bootstrap:
         condition: service_completed_successfully
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - "archivematica_storage_service_staging_data:/var/archivematica/storage_service:rw"
      - "${ARCHIVEMATICA_SS_TRANSFER_SOURCE:-./}:/home:rw"
      - "./AIPsStore:/var/archivematica/sharedDirectory/www/AIPsStore"
      - "./DIPsStore:/var/archivematica/sharedDirectory/www/DIPsStore"
      # Other folders can be mounted to be available in the tranfer source:
      # - "~/Downloads:/home/Downloads"
    links:
      - "mysql"

  archivematica-dashboard:
    image: "artefactual/archivematica-dashboard:v1.18.0"
    platform: "linux/amd64"
    environment: &dashboard-env
    # Full list at https://github.com/artefactual/archivematica/tree/stable/1.18.x/src/dashboard/install#parameter-list
      FORWARDED_ALLOW_IPS: "*"
      AM_GUNICORN_ACCESSLOG: "/dev/null"
      DJANGO_SETTINGS_MODULE: "archivematica.dashboard.settings.local"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_GEARMAN_SERVER: "gearmand:4730"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER: "http://elasticsearch:9200"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_PROMETHEUS_ENABLED: "1"
      ARCHIVEMATICA_DASHBOARD_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_DASHBOARD_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_DASHBOARD_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE: "MCP"
      ARCHIVEMATICA_DASHBOARD_SEARCH_ENABLED: "${AM_SEARCH_ENABLED:-false}"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_AUDIT_LOG_MIDDLEWARE: "true"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_SESSION_COOKIE_SECURE: "false"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_CSRF_COOKIE_SECURE: "false"
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/8000; exit $?;'"
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      archivematica-dashboard-bootstrap:
         condition: service_completed_successfully
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"

    links:
      - "mysql"
      - "gearmand"
      - "archivematica-storage-service"

  archivematica-mcp-server:
    image: "artefactual/archivematica-mcp-server:v1.18.0"
    platform: "linux/amd64"
    environment:
    # Full list at https://github.com/artefactual/archivematica/tree/stable/1.18.x/src/MCPServer/install#parameter-list
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "archivematica.MCPServer.settings.common"
      ARCHIVEMATICA_MCPSERVER_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_MCPSERVER_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_MCPSERVER_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_MCPSERVER_CLIENT_DATABASE: "MCP"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_MCPARCHIVEMATICASERVER: "gearmand:4730"
      ARCHIVEMATICA_MCPSERVER_SEARCH_ENABLED: "${AM_SEARCH_ENABLED:-aips}"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_BIND_PORT: "7999"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/7999; exit $?;'"
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      archivematica-dashboard:
        condition: service_healthy
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - "./AIPsStore:/var/archivematica/sharedDirectory/www/AIPsStore"
      - "./DIPsStore:/var/archivematica/sharedDirectory/www/DIPsStore"
    links:
      - "mysql"
      - "gearmand"

  archivematica-mcp-client:
    image: "artefactual/archivematica-mcp-client:v1.18.0"
    platform: "linux/amd64"
    environment:
    # Full list at https://github.com/artefactual/archivematica/tree/stable/1.18.x/src/MCPClient/install#parameter-list
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "archivematica.MCPClient.settings.common"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_DATABASE: "MCP"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHSERVER: "http://elasticsearch:9200"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_MCPARCHIVEMATICASERVER: "gearmand:4730"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_SEARCH_ENABLED: "${AM_SEARCH_ENABLED:-false}"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT: "${AM_CAPTURE_CLIENT_SCRIPT_OUTPUT:-true}"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER: "clamavd:3310"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_MAX_FILE_SIZE: "42"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_MAX_SCAN_SIZE: "42"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_MAX_STREAM_LENGTH: "100"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_BACKEND: "clamdscanner" # Option: clamdscanner or clamscan;
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_METADATA_XML_VALIDATION_ENABLED: "false"
    depends_on:
      archivematica-mcp-server:
        condition: service_healthy
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"
      - "archivematica-storage-service"


  # Migrations containers
  # We run them always to ensure migrations in new versions take effect

  archivematica-storage-service-migrations:
    image: "artefactual/archivematica-storage-service:v0.24.0"
    platform: "linux/amd64"
    environment: *ss-env
    entrypoint:
       - python3
       - -m
       - archivematica.storage_service.manage
       - migrate
       - --noinput
    depends_on:
      mysql-archivematica-db:
         condition: service_completed_successfully


  archivematica-dashboard-migrations:
    image: "artefactual/archivematica-dashboard:v1.18.0"
    platform: "linux/amd64"
    environment: *dashboard-env
    entrypoint:
       - python3
       - -m
       - archivematica.dashboard.manage
       - migrate
       - --noinput
    depends_on:
      mysql-archivematica-db:
         condition: service_completed_successfully
    links:
      - "mysql"

  # Bootstrap commands
  # Those are only needed the first time the system is registered

  archivematica-storage-service-bootstrap:
    image: "artefactual/archivematica-storage-service:v0.24.0"
    platform: "linux/amd64"
    environment: *ss-env
    entrypoint:
       - python3
       - -m
       - archivematica.storage_service.manage
       - create_user
       - --username=${ARCHIVEMATICA_SS_USER:-test}
       - --password=${ARCHIVEMATICA_SS_PASSWORD:-test}
       - --email=${ARCHIVEMATICA_SS_EMAIL:-test}
       - --api-key=${ARCHIVEMATICA_SS_APIKEY:-test}
       - --superuser
    depends_on:
      archivematica-storage-service-migrations:
         condition: service_completed_successfully

  archivematica-dashboard-bootstrap:
    image: "artefactual/archivematica-dashboard:v1.18.0"
    platform: "linux/amd64"
    environment: *dashboard-env
    entrypoint:
       - python3
       - -m
       - archivematica.dashboard.manage
       - install
       - --username=${ARCHIVEMATICA_DASHBOARD_USER:-test}
       - --password=${ARCHIVEMATICA_DASHBOARD_PASSWORD:-test}
       - --email=${ARCHIVEMATICA_DASHBOARD_EMAIL:-test}
       - --org-name=${ARCHIVEMATICA_DASHBOARD_ORG_NAME:-test}
       - --org-id=${ARCHIVEMATICA_DASHBOARD_ORG_ID:-test}
       - --api-key=${ARCHIVEMATICA_DASHBOARD_API_KEY:-test}
       - --ss-url=http://archivematica-storage-service:8000
       - --ss-user=${ARCHIVEMATICA_SS_USER:-test}
       - --ss-api-key=${ARCHIVEMATICA_SS_APIKEY:-test}
       - --site-url=http://archivematica-dashboard:8000
    depends_on:
      archivematica-dashboard-migrations:
         condition: service_completed_successfully
      archivematica-storage-service:
         condition: service_healthy
      mysql:
         condition: service_healthy
    links:
      - "mysql"
      - "archivematica-storage-service"
