if ($programname == "am-gearman") then {
        action(
                type="omfile"
                FileOwner="syslog"
                FileGroup="syslog"
                File="/var/log/archivematica/gearmand.log"
                FileCreateMode="0644"
        )
	        stop
}
if ($programname == "am-nginx") then {
        action(
                type="omfile"
                FileOwner="syslog"
                FileGroup="syslog"
                File="/var/log/archivematica/nginx.log"
                FileCreateMode="0644"
        )
	        stop
}
if ($programname == "am-mysql") then {
        action(
                type="omfile"
                FileOwner="syslog"
                FileGroup="syslog"
                File="/var/log/archivematica/mysql.log"
                FileCreateMode="0644"
        )
	        stop
}

if ($programname == "am-elasticsearch") then {
        action(
                type="omfile"
                FileOwner="syslog"
                FileGroup="syslog"
                File="/var/log/archivematica/elasticsearch.log"
                FileCreateMode="0644"
        )
	        stop
}

if ($programname == "am-clamav") then {
        action(
                type="omfile"
                FileOwner="syslog"
                FileGroup="syslog"
                File="/var/log/archivematica/clamav.log"
                FileCreateMode="0644"
        )
	        stop
}



if ($programname == "am-mcp-client") then {
        action(
                type="omfile"
                FileOwner="syslog"
                FileGroup="syslog"
                File="/var/log/archivematica/MCPClient.log"
                FileCreateMode="0644"
        )
	        stop
}

if ($programname == "am-mcp-server") then {
        action(
                type="omfile"
                FileOwner="syslog"
                FileGroup="syslog"
                File="/var/log/archivematica/MCPServer.log"
                FileCreateMode="0644"
        )
	        stop
}
if ($programname contains("am-dashboard")) then {
        action(
                type="omfile"
                FileOwner="syslog"
                FileGroup="syslog"
                File="/var/log/archivematica/dashboard.log"
                FileCreateMode="0644"
        )
	        stop
}

if ($programname contains("am-ss")) then {
        action(
                type="omfile"
                FileOwner="syslog"
                FileGroup="syslog"
                File="/var/log/archivematica/ss.log"
                FileCreateMode="0644"
        )
	        stop
}


