volumes:
  elasticsearch_data:
    name: "am_elasticsearch8_data"

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.19.3"
    environment:
      - "cluster.name=am-cluster"
      - "node.name=am-node"
      - "network.host=0.0.0.0"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.routing.allocation.disk.threshold_enabled=${ELASTICSEARCH_DISK_THRESHOLD_ENABLED:-true}"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -fsSL http://localhost:9200/_cat/health?h=status | sed -r 's/^[[:space:]]+|[[:space:]]+$//g' | grep -q -E 'green|yellow'",
      ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 65s
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    ports:
      - "127.0.0.1:62002:9200"
